from main.models import Twitter, RedditPostTable, RedditCommentTable, Github


async def populate_twitter():
    await Twitter.bulk_create(
        [
            Twitter(
                tweet_id=1213245124,
                tweet="Hey first tweet! Great!",
                posted_at="2021-03-01",
                likes=50,
                retweets=32,
                sentiment_score=0.7,
                asa_id="ChoiceCoin",
            ),
            Twitter(
                tweet_id=1611245324,
                tweet="Hey! Second tweet!",
                posted_at="2021-03-06",
                likes=3,
                retweets=12,
                sentiment_score=0.4,
                asa_id="ChoiceCoin",
            ),
            Twitter(
                tweet_id=1213245107,
                tweet="Third tweet! Just there",
                posted_at="2021-03-08",
                likes=5,
                retweets=45,
                sentiment_score=0.6,
                asa_id="ChoiceCoin",
            ),
            Twitter(
                tweet_id=1213245891,
                tweet="Bad!!",
                posted_at="2021-03-15",
                likes=0,
                retweets=2,
                sentiment_score=0.3,
                asa_id="ChoiceCoin",
            ),
            Twitter(
                tweet_id=4321451234,
                tweet="Bad, not good!",
                posted_at="2021-03-21",
                likes=0,
                retweets=4,
                sentiment_score=0.3,
                asa_id="ChoiceCoin",
            ),
            Twitter(
                tweet_id=12144333124,
                tweet="Hey first tweet! Great!",
                posted_at="2021-07-6",
                likes=50,
                retweets=32,
                sentiment_score=0.7,
                asa_id="YieldlyFinance",
            ),
            Twitter(
                tweet_id=16112478903,
                tweet="Hey! Second tweet!",
                posted_at="2022-03-06",
                likes=3,
                retweets=12,
                sentiment_score=0.4,
                asa_id="YieldlyFinance",
            ),
            Twitter(
                tweet_id=1213246701,
                tweet="Third tweet! Just there",
                posted_at="2021-03-08",
                likes=5,
                retweets=45,
                sentiment_score=0.6,
                asa_id="YieldlyFinance",
            ),
            Twitter(
                tweet_id=12132454854,
                tweet="Bad!!",
                posted_at="2021-03-15",
                likes=0,
                retweets=2,
                sentiment_score=0.3,
                asa_id="YieldlyFinance",
            ),
            Twitter(
                tweet_id=432156671234,
                tweet="Bad, not good!",
                posted_at="2022-03-21",
                likes=0,
                retweets=4,
                sentiment_score=0.3,
                asa_id="YiedlyFinance",
            ),
        ]
    )


async def populate_post():
    await RedditPostTable.bulk_create(
        [
            RedditPostTable(
                post_id="Ruimax4",
                title="Apple's new M2",
                text="Have you seen the new M2??",
                score=12673,
                num_of_comments=3,
                time_created="2022-06-06",
                url="apple.com",
                sentiment_score=0.9,
                asa_id="ChoiceCoin",
            ),
            RedditPostTable(
                post_id="cui6ax4",
                title="Kilo se choice coin",
                text="choice coin dey dip like mad",
                score=223,
                num_of_comments=2,
                time_created="2022-04-26",
                url="getpost.com",
                sentiment_score=0.3,
                asa_id="ChoiceCoin",
            ),
            RedditPostTable.create(
                post_id="auiwes4",
                title="Great Post",
                text="Heyy! Yo! This coin is to the moon !!",
                score=41,
                num_of_comments=5,
                time_created="2021-02-28",
                url="getpost.com",
                sentiment_score=0.8,
                asa_id="YieldlyFinance",
            ),
        ]
    )


async def populate_comments():
    await RedditCommentTable.bulk_create(
        [
            RedditCommentTable(
                comment_id="iegedo3e8",
                body="comment 1",
                score=50,
                time_created="2021-03-01",
                sentiment_score=0.7,
                post_id="auiwes4",
            ),
            RedditCommentTable(
                comment_id="iegeddfde8",
                body="comment 2",
                score=3,
                time_created="2021-03-06",
                sentiment_score=0.4,
                post_id="auiwes4",
            ),
            RedditCommentTable(
                comment_id="iegd3e4548",
                body="comment 3",
                score=5,
                time_created="2021-03-08",
                sentiment_score=0.6,
                post_id="auiwes4",
            ),
            RedditCommentTable(
                comment_id="i334edo3e8",
                body="comment 4",
                score=0,
                time_created="2021-03-15",
                sentiment_score=0.3,
                post_id="auiwes4",
            ),
            RedditCommentTable(
                comment_id="iejjed3e8",
                body="comment 5",
                score=0,
                time_created="2021-03-21",
                sentiment_score=0.3,
                post_id="auiwes4",
            ),
            RedditCommentTable(
                comment_id="iegeyhsdj8",
                body="omooor! Na mind blowing oo",
                score=50,
                time_created="2022-06-06",
                sentiment_score=0.7,
                post_id="Ruimax4",
            ),
            RedditCommentTable(
                comment_id="rfyyiddfde8",
                body="I for like cop the 16gb variant, but money no dey",
                score=78,
                time_created="2022-06-07",
                sentiment_score=0.4,
                post_id="Ruimax4",
            ),
            RedditCommentTable(
                comment_id="ghjkk3e4548",
                body="indifferent",
                score=5,
                time_created="2022-06-07",
                sentiment_score=0.5,
                post_id="Ruimax4",
            ),
            RedditCommentTable(
                comment_id="stkkiiedo3e8",
                body="Omooor! I had high hopes, quite sad",
                score=7,
                time_created="2021-09-15",
                sentiment_score=0.3,
                post_id="cui6ax4",
            ),
            RedditCommentTable(
                comment_id="hdjisd3e8",
                body="Sadly it is the reality",
                score=0,
                time_created="2021-08-22",
                sentiment_score=0.3,
                post_id="cui6ax4",
            ),
        ]
    )


async def populate_github():
    await Github.bulk_create(
        [
            Github(
                repo_name="repo1",
                repo_desc="desc 1",
                date_created="2020-07-05",
                last_push_date="2021-03-01",
                language="rust",
                no_of_forks=6,
                no_of_stars=24,
                no_of_watches=22,
                no_of_contributors=7,
                no_of_commits=14,
                issues=5,
                pull_requests=13,
                asa_id="YieldlyFinance",
            ),
            Github(
                repo_name="repo2",
                repo_desc="desc 2",
                date_created="2021-02-01",
                last_push_date="2022-04-01",
                language="ruby",
                no_of_forks=3,
                no_of_stars=50,
                no_of_watches=12,
                no_of_contributors=4,
                no_of_commits=20,
                issues=11,
                pull_requests=41,
                asa_id="YieldlyFinance",
            ),
            Github(
                repo_name="repo3",
                repo_desc="desc 3",
                date_created="2022-01-31",
                last_push_date="2022-04-30",
                language="scala",
                no_of_forks=3,
                no_of_stars=50,
                no_of_watches=18,
                no_of_contributors=20,
                no_of_commits=20,
                issues=5,
                pull_requests=17,
                asa_id="YieldlyFinance",
            ),
            Github(
                repo_name="repo-00",
                repo_desc="desc -01",
                date_created="2021-08-05",
                last_push_date="2022-03-01",
                language="rust",
                no_of_forks=6,
                no_of_stars=24,
                no_of_watches=22,
                no_of_contributors=7,
                no_of_commits=14,
                issues=5,
                pull_requests=13,
                asa_id="ChoiceCoin",
            ),
            Github(
                repo_name="repo-02",
                repo_desc="desc 02",
                date_created="2021-02-21",
                last_push_date="2022-04-23",
                language="ruby",
                no_of_forks=3,
                no_of_stars=50,
                no_of_watches=12,
                no_of_contributors=4,
                no_of_commits=20,
                issues=11,
                pull_requests=41,
                asa_id="ChoiceCoin",
            ),
            Github(
                repo_name="repo-03",
                repo_desc="desc 03",
                date_created="2022-04-30",
                last_push_date="2022-05-31",
                language="scala",
                no_of_forks=3,
                no_of_stars=50,
                no_of_watches=18,
                no_of_contributors=20,
                no_of_commits=20,
                issues=5,
                pull_requests=17,
                asa_id="ChoiceCoin",
            ),
        ]
    )
